# Copyright 2013-2020 Lawrence Livermore National Security, LLC and other
# Spack Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: (Apache-2.0 OR MIT)

generate ci jobs:
  script:
    - "./bin/generate-gitlab-ci-yml.sh"
  tags:
    - "spack-pre-ci"
  artifacts:
    paths:
      - ci-generation
    when: always
